# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo good evening

    # json取得
    - name: get json
      run: |
        curl -L -X GET https://script.google.com/macros/s/AKfycbyWPWVeFrTwIJCbKFTLtchMhZlqM8qpA8QxlGXEixZiQeTcQaHu/exec > ./assets/json/activity.json
        git config --global user.email "yamazaki-engines@gmail.com"
        git config --global user.name yamazaki-engines 
        git commit -m “JSON更新” ./assets/json/activity.json
        gid push origin master
